### ISSUE TITLE
Minor: re-used code still has old text: 

### ISSUE THREAD

**Issue by LuisEJaar** [IAmLuisJ/Grumbl#1]
![GrumblingOnGrumble](https://user-images.githubusercontent.com/75051583/179011181-bc98f080-46e2-43ab-99c8-b441c94eb7a0.JPG)

**Comment by IAmLuisJ** [comment]
Hey Luis! Thank you for catching this! yeah I reused the photospots page and didn't finish updating it I guess. This repo is for the iOS prototype written in swift. I've updated the landing page to include the correct wording. Thanks again!
